/// Information about the [ConceptMap/$closure](conceptmap-operation-closure.html) operation.
Class HS.FHIR.DTL.vR4.Model.Element.TerminologyCapabilities.closure Extends HS.FHIR.DTL.vR4.Model.Base.BackboneElement [ Not ProcedureBlock ]
{

/// boolean
/// <p>
/// If cross-system closure is supported.
Property translation As %Boolean(XMLNAME = "translation", XMLPROJECTION = "ATTRIBUTE");

Parameter ELEMENTQUALIFIED = 1;

Parameter XMLNAME = "TerminologyCapabilities.closure";

Parameter XMLPROJECTION = "ELEMENT";

Parameter XMLSEQUENCE = 1;

Parameter XMLTYPE = "TerminologyCapabilities.closure";

}
