/// *** <b>THIS CLASS IS DEPRECATED.</b> Please use HS.FHIR.<b>vDSTU2.</b>Model.Datatype.CodePrimitive when working with FHIR DSTU2.
Class HS.FHIR.Model.Datatype.CodePrimitive Extends %String [ Deprecated, ProcedureBlock ]
{

///  
Parameter JSONTYPEFIELD;

///  
Parameter ELEMENTQUALIFIED = 1;

///  
Parameter MAXLEN;

///  
Parameter MINLEN = 1;

///  
Parameter XMLPATTERN = "[^\s]+([\s][^\s]+)*";

}
