/// *** <b>THIS CLASS IS DEPRECATED.</b> Please use HS.FHIR.<b>vDSTU2.</b>Model.Datatype.IdPrimitive when working with FHIR DSTU2.
Class HS.FHIR.Model.Datatype.IdPrimitive Extends %String [ Deprecated, ProcedureBlock ]
{

///  
Parameter JSONTYPEFIELD;

///  
Parameter ELEMENTQUALIFIED = 1;

///  
Parameter MAXLEN;

///  
Parameter MINLEN = 1;

///  
Parameter XMLPATTERN = "[A-Za-z0-9\-\.]{1,64}";

}
