/// *** <b>THIS CLASS IS DEPRECATED.</b> Please use HS.FHIR.<b>vDSTU2.</b>Model.Datatype.OidPrimitive when working with FHIR DSTU2.
Class HS.FHIR.Model.Datatype.OidPrimitive Extends %xsd.anyURI [ Deprecated, ProcedureBlock ]
{

///  
Parameter JSONTYPEFIELD;

///  
Parameter ELEMENTQUALIFIED = 1;

///  
Parameter MINLEN = 1;

///  
Parameter XMLPATTERN = "urn:oid:(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*";

}
