/// *** <b>THIS CLASS IS DEPRECATED.</b> Please use HS.FHIR.<b>vDSTU2.</b>Model.Datatype.TimePrimitive when working with FHIR DSTU2.
Class HS.FHIR.Model.Datatype.TimePrimitive Extends %String [ Deprecated, ProcedureBlock ]
{

///  
Parameter JSONTYPEFIELD;

///  
Parameter ELEMENTQUALIFIED = 1;

///  
Parameter MAXLEN;

///  
Parameter XMLPATTERN = "([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?";

}
