ROUTINE EnsEDISEFErrors [Type=INC]
#define EnsEDISEFFileNotExists      "<EnsEDISEF>FileNotExists"
	; Copyright (c) 2020 by InterSystems Corporation.
	; Cambridge, Massachusetts, U.S.A.  All rights reserved.
	; Confidential property of InterSystems Corporation.
#define EnsEDISEFNodeEnumeration    "<EnsEDISEF>NodeEnumeration"
#define EnsEDISEFNodeIdentification "<EnsEDISEF>NodeIdentification"
#define EnsEDISEFNodeValidation     "<EnsEDISEF>NodeValidation"