Class HS.FHIR.vDSTU2.Model.Resource.TestScript.Action2 Extends HS.FHIR.vDSTU2.Model.Base.BackboneElement [ ProcedureBlock ]
{

Parameter JSONTYPEFIELD;

Parameter ELEMENTQUALIFIED = 1;

Parameter XMLNAME = "TestScript.Action2";

Parameter XMLSEQUENCE = 1;

Parameter XMLTYPE = "TestScript.Action2";

/// An operation would involve a REST request to a server.
Property operation As HS.FHIR.vDSTU2.Model.Resource.TestScript.Operation(XMLNAME = "operation");

}
